# Generated by Django 5.2 on 2025-04-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelineitem",
            name="year",
            field=models.CharField(max_length=30),
        ),
    ]
